# -*- coding: utf-8 -*-
"""Test Reconocimiento de imagenes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M4vXMhUWsy8_SXKYAHr_Kg0WIpmK6G80

# ***Se hace la primera prueba***
"""

import numpy as np
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

test_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/Fruit_Vegetable_Recognition/Test',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(64, 64),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

#Se carga el modelo hecho previamente

cnn = tf.keras.models.load_model('/content/trained_model.h5')

#Predicción en una imagen - Se carga la imagen

import cv2 

image_path = '/content/drive/MyDrive/Fruit_Vegetable_Recognition/Test/apple_red_1/r0_103.jpg'

img = cv2.imread(image_path)[:,:,::-1]

plt.imshow(img)

plt.title('Prueba Manzana')

plt.xticks([])

plt.yticks([])

plt.show()

#Se hace la prueba

image = tf.keras.preprocessing.image.load_img(image_path,target_size=(64,64))
input_arr = tf.keras.preprocessing.image.img_to_array(image)
input_arr = np.array([input_arr])  # batch -> Realiza la predicción
predictions = cnn.predict(input_arr)

result_index = np.where(predictions[0] == max(predictions[0]))
print(result_index)

print("La fruta es: {}".format(test_set.class_names[result_index[0][0]]))

"""# ***Segunda prueba***"""

#Predicción en una imagen - Se carga la imagen

import cv2 

image_path2 = '/content/drive/MyDrive/Fruit_Vegetable_Recognition/Test/carrot_1/r0_103.jpg'

img2 = cv2.imread(image_path2)[:,:,::-1]

plt.imshow(img2)

plt.title('Prueba Zanahoria')

plt.xticks([])

plt.yticks([])

plt.show()

#Se hace la prueba

image2 = tf.keras.preprocessing.image.load_img(image_path2,target_size=(64,64))
input_arr = tf.keras.preprocessing.image.img_to_array(image2)
input_arr = np.array([input_arr])  # Convert single image to a batch.
predictions = cnn.predict(input_arr)

result_index = np.where(predictions[0] == max(predictions[0]))
print(result_index)

print("La fruta es: {}".format(test_set.class_names[result_index[0][0]]))

"""# ***Prueba - Pera***"""

#Predicción en una imagen - Se carga la imagen

import cv2 

image_path3 = '/content/drive/MyDrive/Fruit_Vegetable_Recognition/Test/pear_3/r0_103.jpg'

img3 = cv2.imread(image_path3)[:,:,::-1]

plt.imshow(img3)

plt.title('Prueba Pera')

plt.xticks([])

plt.yticks([])

#Se hace la prueba

image3 = tf.keras.preprocessing.image.load_img(image_path3,target_size=(64,64))
input_arr = tf.keras.preprocessing.image.img_to_array(image3)
input_arr = np.array([input_arr])  # Convert single image to a batch.
predictions = cnn.predict(input_arr)

result_index = np.where(predictions[0] == max(predictions[0]))
print(result_index)

print("La fruta es: {}".format(test_set.class_names[result_index[0][0]]))